import './globals.css'
import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Script from 'next/script';

config.autoAddCss = false

const dosis = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Logging App',
  description: 'Generated by Nora + Code',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-KSXSX0L943" />
          <Script id="google-analytics">
            {`
            window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
  
              gtag('config', 'G-KSXSX0L943');
            `}
          </Script>
        <html lang="en">
          <body className={dosis.className}>{children}</body>
        </html>
      </>
  )
}
