import './globals.css'
import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

const dosis = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Logging App',
  description: 'Generated by Nora + Code',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dosis.className}>{children}</body>
    </html>
  )
}
